version: '3.9'
services:

  keycloak-1:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak-1
    ports:
      - 8097:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-realm-1.json
    volumes:
      - ./keycloak/demo-realm-1.json:/tmp/demo-realm-1.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak-1:8080/auth/realms/demo-realm-1/.well-known/openid-configuration"]
      interval: 10s
      timeout: 10s
      retries: 15

  keycloak-2:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak-2
    ports:
      - 8098:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-realm-2.json
    volumes:
      - ./keycloak/demo-realm-2.json:/tmp/demo-realm-2.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak-2:8080/auth/realms/demo-realm-2/.well-known/openid-configuration"]
      interval: 10s
      timeout: 10s
      retries: 15