version: '3.9'
services:

  spring-security-multiple-issuers:
    image: michaelruocco/spring-security-multiple-issuers:latest
    container_name: spring-security-multiple-issuers
    profiles: [ "local-app-docker" ]
    restart: on-failure
    ports:
      - 8099:80
    environment:
      - SERVER_PORT=80
      - SPRING_PROFILES_ACTIVE=default
      - AUTH_ISSUER_1_URI=http://keycloak-1:8097/auth/realms/demo-realm-1
      - AUTH_ISSUER_1_AUDIENCE=demo-realm-1-audience
      - AUTH_ISSUER_2_URI=http://keycloak-2:8098/auth/realms/demo-realm-2
      - AUTH_ISSUER_2_AUDIENCE=demo-realm-2-audience
    depends_on:
      - keycloak-1
      - keycloak-2

  keycloak-1:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak-1
    command: ["-Djboss.http.port=8097"]
    ports:
      - 8097:8097
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-realm-1.json
    volumes:
      - ./keycloak/demo-realm-1.json:/tmp/demo-realm-1.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak-1:8097/auth/realms/demo-realm-1/.well-known/openid-configuration"]
      interval: 10s
      timeout: 10s
      retries: 15

  keycloak-2:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak-2
    command: ["-Djboss.http.port=8098"]
    ports:
      - 8098:8098
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-realm-2.json
    volumes:
      - ./keycloak/demo-realm-2.json:/tmp/demo-realm-2.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak-2:8098/auth/realms/demo-realm-2/.well-known/openid-configuration"]
      interval: 10s
      timeout: 10s
      retries: 15