spring.security.oauth2.resourceserver:
  issuers:
    - uri: ${auth.issuer.1.uri:http://localhost:8097/auth/realms/demo-realm-1}
      audience: ${auth.issuer.1.audience:demo-realm-1-audience}
    - uri: ${auth.issuer.2.uri:http://localhost:8098/auth/realms/demo-realm-2}
      audience: ${auth.issuer.2.audience:demo-realm-2-audience}

logging.level:
  org.springframework.security: DEBUG